name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build

  # The dump sources task needs to be run after merging AGP version updates.
  dump-sources:
    runs-on: ubuntu-latest
    # TODO: add `github.event.repository.fork == false` check back after https://github.com/jrodbx/agp-sources/pull/9 is merged.
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          rm -rf *-alpha* # Remove the last alpha version sources.
          ./gradlew dumpSources
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            Update AGP sources to the latest

            _Auto-generated by `dump-sources` Github workflow._
          title: Update AGP sources to the latest
          body: _Auto-generated by `dump-sources` Github workflow._
          branch: actions/dump-sources
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> # Same as `committer`.
          delete-branch: true
